### ISSUE TITLE
doesnot work on `find` and `create` action

### ISSUE THREAD

**Issue by elixiao** [stalniy/casl-feathersjs-example#1]
I want to restrict some role to `find` and `create` posts, so I wrote the following code:

```
cannot('find','posts')
cannot('create', 'posts')
```

however it doesn't work, I can still `find` and `create` posts

**Comment by stalniy** [comment]
There is a bug with create in this repo. It was discussed in the comments of the article on medium. To restrict `find` you need to restrict `read` operation. I will try to help you when a bit later as currently I don't have my laptop

Meanwhile you can check example for Expressjs app. You can find it in my repos on GitHub

**Comment by elixiao** [comment]
@stalniy thanks for your reply. restrict `read` doesn't work for me either, but I found a workaround to return empty array for unauthorized request:

```
can('find', 'posts', {notExistField: true})
```
I couldn't find a workaround for method `create`. Hope fix it soon, thanks again for your excellent casl repo.

**Comment by stalniy** [comment]
@elixiao I pushed a fix for this issues. There is a bit better way to restrict collection for read by using `$limit = 0`. I put my thoughts on this topic [in comments](https://github.com/stalniy/casl-feathersjs-example/blob/master/src/hooks/abilities.js#L60). 

**Update**: please check and close the issue if everything is ok :)
