### ISSUE TITLE
Update to Feathers 3.x

### ISSUE THREAD

**Issue by poupryc** [stalniy/casl-feathersjs-example#5]
Hello

I am a beginner in the use of feathers and I see that this project uses version 2. I don't know if the use of CASL is the same in v3 (especially when calling in a hook a service)

Thank !

**Comment by stalniy** [comment]
Hello 

I'm also not sure wether it will work in 3.x. 

But if you have time to check this and create a PR, that would be awesome!

Anyway casl doesn't depend on feathers, so you are welcome to read documention and place required checks in appropriate places :)

Thanks for using CASL!

**Comment by poupryc** [comment]
In fact, I'm not even sure how to convert the existing system to feathersjs 3. The Hook system to check the role remains a bit mystical for me, especially the part where the Hook will call the service. CASL is incredible, but its integration into feathersjs is a bit more complicated. I think I'm going to wait for a version working on version 3 before I can analyze the code.

thank you for your work !

**Comment by mattbradbury** [comment]
I did a quick and dirty fork that upgraded it to v3 if anyone wants to take a look.
https://github.com/mattbradbury/casl-feathersjs-example

It's also a pull request on here. 

My first github pull request!!!!

**Comment by stalniy** [comment]
closed by #7 

Thanks for using CASL!
