### ISSUE TITLE
Nested document key example

### ISSUE THREAD

**Issue by adrianofoschi** [stalniy/casl-feathersjs-example#8]
Hi, I'm trying to use your example (with mongoose) for my use case:

**Domain definition:**
A "User" could has more "Vehicles"
A "Document" must have a "Vehicle"

**Schema definition:**
```
vehicle { users: [ {type: objectId, ref: 'user'} ] }
document { vehicle: {type: objectId, ref: 'vehicle' }}
```

**Rule definition**
I successfully defined an ability for user to read/update only his vehicles 
`can(['read', 'update'], 'vehicle', { users: { $in: [user._id] } } )`

How can I define a rule to check "user can read/update only documents of his vehicles" ?
I tried with:

`can(['read', 'update'], 'document', { "vehicle.users": { $in: [user._id] } } )`

Obviously with no success. Can you provide "more nested level" example?
Thanks you

**Comment by stalniy** [comment]
Answered in gitter, so this may be closed. Thanks for using CASL!

Lets continue discussion in gitter :)

**Answer**:

Hi @adrianofoschi ,

casl don't manage references on related documents. You need to do it yourself.

So, I see few ways:
1. Retrieve ids of all vehicles when you define rules. This works good in case if amount of vehicles not big (<= 1000)

```js
const vehicleIds = await getVehicleIds(user)

can(['read', 'update'], 'document', { vehicle: { $in: vehicleIds } })
```

2. Denormalize your scheme. For example, add additional `user_id` field to vehicle document
3. Think whether you can embed document as subdocument to vechicle, something like this:
```js
vehicle {
  documents: [Document],
  users: [ {type: objectId, ref: 'user'} ]
}
```
4. Just don't define rule per documents and enforce them in routes (REST or GraphQL doesn't matter).

```js
// app - express app

app.get('/vehicle/:id/documents', async (req, res) => {
   const vehicle = await Vehicle.findById(req.params.id)

   req.ability.throwUnlessCan('read', vehicle)
   const documents = Document.find({ vehicle: vehicle.id })

   res.send({ documents })
})
```
